### ISSUE TITLE
[Bug]: Indexing error on `full_load_once_audio`, specific duration

### ISSUE THREAD

**Issue by bigfoodK** [NamseEnt/namseent#765]
### Expected Behavior

Play `full_load_once_audio`

### Actual Behavior

panic with
```text
thread '<unnamed>' panicked at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\alloc\src\vec\mod.rs:2046:36:
range end index 942 out of range for slice of length 868
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Steps to Reproduce

1. Go to `namui/sample/media`
2. Change duration slice duration to be like below
   https://github.com/NamseEnt/namseent/blob/547644544d1a069e394d205c3a2b616847954098/namui/sample/media/src/lib.rs#L44-L47
   to
   ```rust
   set_sliced_audio.set(Some(opus.slice(1.sec()..(1.sec() + 1001.ms())).unwrap()));
   ```

**Comment by namse** [comment]
Show me device setting in log like below

```
[namui-media] Device supports format WaveFormat { nAvgBytesPerSec: 352800, cbSize: 22, nBlockAlign: 8, wBitsPerSample: 32, nSamplesPerSec: 44100, wFormatTag: 65534, wValidBitsPerSample: 32, SubFormat: 00000003-0000-0010-8000-00AA00389B71, nChannel: 2, dwChannelMask: 3 }
```

**Comment by bigfoodK** [comment]
full log
```text
Window created
[namui-media] Device doesn't support format:
WaveFormat {
    nAvgBytesPerSec: 352800,
    cbSize: 22,
    nBlockAlign: 8,
    wBitsPerSample: 32,
    nSamplesPerSec: 44100,
    wFormatTag: 65534,
    wValidBitsPerSample: 32,
    SubFormat: 00000003-0000-0010-8000-00AA00389B71,
    nChannel: 2,
    dwChannelMask: 3,
}
Closest match is:
WaveFormat {
    nAvgBytesPerSec: 4608000,
    cbSize: 22,
    nBlockAlign: 24,
    wBitsPerSample: 32,
    nSamplesPerSec: 192000,
    wFormatTag: 65534,
    wValidBitsPerSample: 32,
    SubFormat: 00000003-0000-0010-8000-00AA00389B71,
    nChannel: 6,
    dwChannelMask: 63,
}
Namui system initialized
Start event loop
[mp3 @ 00000267CDD4D3C0] Estimating duration from bitrate, this may be inaccurate
mp3 loaded
[mp3 @ 00000267CDD47640] Estimating duration from bitrate, this may be inaccurate
opus loaded
[opus @ 00000267CE685380] Could not update timestamps for skipped samples.
[opus @ 00000267D4033180] Could not update timestamps for skipped samples.
[opus @ 00000267D4033180] Could not update timestamps for discarded samples.
full load once audio loaded
mp4 loaded
thread '<unnamed>' panicked at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\alloc\src\vec\mod.rs:2046:36:
range end index 882 out of range for slice of length 44
stack backtrace:
   0:     0x7ff67b296a0a - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\sys_common\backtrace.rs:44
   1:     0x7ff67b2aabfb - core::fmt::rt::Argument::fmt
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\core\src\fmt\rt.rs:138
   2:     0x7ff67b2aabfb - core::fmt::write
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\core\src\fmt\mod.rs:1114
   3:     0x7ff67b292311 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\io\mod.rs:1763
   4:     0x7ff67b29678a - std::sys_common::backtrace::_print
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\sys_common\backtrace.rs:47
   5:     0x7ff67b29678a - std::sys_common::backtrace::print
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\sys_common\backtrace.rs:34
   6:     0x7ff67b298e5a - std::panicking::default_hook::closure$1
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:272
   7:     0x7ff67b298ac8 - std::panicking::default_hook
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:292
   8:     0x7ff67b299508 - std::panicking::rust_panic_with_hook
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:731
   9:     0x7ff67b2993ed - std::panicking::begin_panic_handler::closure$0
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:609
  10:     0x7ff67b2973f9 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\sys_common\backtrace.rs:170
  11:     0x7ff67b299100 - std::panicking::begin_panic_handler
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:597
  12:     0x7ff67cd29277 - core::panicking::panic_fmt
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\core\src\panicking.rs:72
  13:     0x7ff67cd29934 - core::slice::index::slice_end_index_len_fail_rt
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\core\src\slice\index.rs:76
  14:     0x7ff67cd29934 - core::slice::index::slice_end_index_len_fail
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\core\src\slice\index.rs:68
  15:     0x7ff67b5016b7 - core::slice::index::range<core::ops::range::RangeTo<usize> >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\core\src\slice\index.rs:723
  16:     0x7ff67b350afb - alloc::vec::Vec<f32,alloc::alloc::Global>::drain<f32,alloc::alloc::Global,core::ops::range::RangeTo<usize> >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\alloc\src\vec\mod.rs:2046
  17:     0x7ff67b41542c - namui::namui::system::media::audio::full_load_once_audio::impl$1::consume
                               at /home/bigfood/programming/namseent/namui/namui/src/namui/system/media/audio/full_load_once_audio.rs:122
  18:     0x7ff67b4e8219 - namui::namui::system::media::audio::audio_context::impl$0::new::closure$1
                               at /home/bigfood/programming/namseent/namui/namui/src/namui/system/media/audio/audio_context.rs:74
  19:     0x7ff67b4c69e9 - std::sys_common::backtrace::__rust_begin_short_backtrace<namui::namui::system::media::audio::audio_context::impl$0::new::closure_env$1,tuple$<> >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\sys_common\backtrace.rs:154
  20:     0x7ff67b4c69e9 - std::sys_common::backtrace::__rust_begin_short_backtrace<namui::namui::system::media::audio::audio_context::impl$0::new::closure_env$1,tuple$<> >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\sys_common\backtrace.rs:154
  21:     0x7ff67b50d331 - std::thread::impl$0::spawn_unchecked_::closure$1::closure$0<namui::namui::system::media::audio::audio_context::impl$0::new::closure_env$1,tuple$<> >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\thread\mod.rs:529
  22:     0x7ff67b9eb0c1 - core::panic::unwind_safe::impl$23::call_once<tuple$<>,std::thread::impl$0::spawn_unchecked_::closure$1::closure_env$0<namui::namui::system::media::audio::audio_context::impl$0::new::closure_env$1,tuple$<> > >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\core\src\panic\unwind_safe.rs:271
  23:     0x7ff67b80b24b - std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::impl$0::spawn_unchecked_::closure$1::closure_env$0<namui::namui::system::media::audio::audio_context::impl$0::new::closure_env$1,tuple$<> > >,tuple$<> >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\panicking.rs:504
  24:     0x7ff67b80caa3 - std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<std::sys::common::thread_local::fast_local::destroy_value::closure_env$0<core::cell::RefCell<std::collections::hash::set::HashSet<namui::namui::hooks::sig::SigId,std::collections::ha
  25:     0x7ff67b809b34 - std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<std::thread::impl$0::spawn_unchecked_::closure$1::closure_env$0<namui::namui::system::media::audio::audio_context::impl$0::new::closure_env$1,tuple$<> > > >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\panicking.rs:468
  26:     0x7ff67b50cd33 - std::panic::catch_unwind
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\panic.rs:142
  27:     0x7ff67b50cd33 - std::thread::impl$0::spawn_unchecked_::closure$1<namui::namui::system::media::audio::audio_context::impl$0::new::closure_env$1,tuple$<> >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\thread\mod.rs:528
  28:     0x7ff67b354b1e - core::ops::function::FnOnce::call_once<std::thread::impl$0::spawn_unchecked_::closure_env$1<namui::namui::system::media::audio::audio_context::impl$0::new::closure_env$1,tuple$<> >,tuple$<> >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\core\src\ops\function.rs:250
  29:     0x7ff67b29db5c - std::sys::windows::thread::impl$0::new::thread_start
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\sys\windows\thread.rs:57
  30:     0x7ffb449a257d - BaseThreadInitThunk
  31:     0x7ffb4502aa58 - RtlUserThreadStart
```
