### ISSUE TITLE
[Bug]: Can not draw image

### ISSUE THREAD

**Issue by bigfoodK** [NamseEnt/namseent#772]
### Expected Behavior

Draw image with `namui::image()`

### Actual Behavior

panic with below
```text
thread '<unnamed>' panicked at /home/bigfood/programming/namseent/namui/namui/src/namui/system/skia/non_wasm.rs:30:9:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
stack backtrace:
   0:     0x7ff7009b508a - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\sys_common\backtrace.rs:44
   1:     0x7ff7009e365b - core::fmt::rt::Argument::fmt
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\core\src\fmt\rt.rs:138
   2:     0x7ff7009e365b - core::fmt::write
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\core\src\fmt\mod.rs:1114
   3:     0x7ff7009b0991 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\io\mod.rs:1763
   4:     0x7ff7009b4e0a - std::sys_common::backtrace::_print
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\sys_common\backtrace.rs:47
   5:     0x7ff7009b4e0a - std::sys_common::backtrace::print
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\sys_common\backtrace.rs:34
   6:     0x7ff7009b74da - std::panicking::default_hook::closure$1
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:272
   7:     0x7ff7009b7148 - std::panicking::default_hook
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:292
   8:     0x7ff7009b7b88 - std::panicking::rust_panic_with_hook
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:731
   9:     0x7ff7009b7a6d - std::panicking::begin_panic_handler::closure$0
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:609
  10:     0x7ff7009b5a79 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\sys_common\backtrace.rs:170
  11:     0x7ff7009b7780 - std::panicking::begin_panic_handler
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:597
  12:     0x7ff7023861a7 - core::panicking::panic_fmt
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\core\src\panicking.rs:72
  13:     0x7ff700cdd6e2 - core::panicking::panic_display<tokio::runtime::handle::TryCurrentError>
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\core\src\panicking.rs:168
  14:     0x7ff700d59dbb - tokio::task::spawn::spawn_inner<enum2$<namui::namui::system::skia::non_wasm::render::closure$0::async_block_env$0> >
                               at /home/bigfood/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/task/spawn.rs:203
  15:     0x7ff700d59f18 - tokio::task::spawn::spawn<enum2$<namui::namui::system::skia::non_wasm::render::closure$0::async_block_env$0> >
                               at /home/bigfood/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/task/spawn.rs:174
  16:     0x7ff700d9aa45 - namui::namui::system::skia::non_wasm::render::closure$0
                               at /home/bigfood/programming/namseent/namui/namui/src/namui/system/skia/non_wasm.rs:30
  17:     0x7ff700f77e77 - namui_drawer_sys::draw::closure$0
                               at /home/bigfood/programming/namseent/namui/namui-drawer/sys/src/lib.rs:15
  18:     0x7ff7011bbeeb - namui_drawer_sys::draw::image::impl$0::draw
                               at /home/bigfood/programming/namseent/namui/namui-drawer/sys/src/draw/image.rs:6
  19:     0x7ff70107177d - namui_drawer_sys::draw::impl$3::draw
                               at /home/bigfood/programming/namseent/namui/namui-drawer/sys/src/draw/mod.rs:141
  20:     0x7ff70106fffb - namui_drawer_sys::draw::impl$2::draw::closure$0
                               at /home/bigfood/programming/namseent/namui/namui-drawer/sys/src/draw/mod.rs:132
  21:     0x7ff700f9a263 - core::iter::traits::iterator::Iterator::for_each::call::closure$0<enum2$<namui_type::types::render::command::DrawCommand>,namui_drawer_sys::draw::impl$2::draw::closure_env$0>
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\core\src\iter\traits\iterator.rs:854
  22:     0x7ff700e17108 - core::iter::traits::iterator::Iterator::fold<alloc::vec::into_iter::IntoIter<enum2$<namui_type::types::render::command::DrawCommand>,alloc::alloc::Global>,tuple$<>,core::iter::traits::iterator::Iterator::for_each::call::closure_env$0<enum2$<namui_type::ty
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\core\src\iter\traits\iterator.rs:2639
  23:     0x7ff700e171d6 - core::iter::traits::iterator::Iterator::for_each<alloc::vec::into_iter::IntoIter<enum2$<namui_type::types::render::command::DrawCommand>,alloc::alloc::Global>,namui_drawer_sys::draw::impl$2::draw::closure_env$0>
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\core\src\iter\traits\iterator.rs:857
  24:     0x7ff701050910 - namui_drawer_sys::draw::impl$2::draw
                               at /home/bigfood/programming/namseent/namui/namui-drawer/sys/src/draw/mod.rs:130
  25:     0x7ff70106ffbb - namui_drawer_sys::draw::impl$1::draw::draw_internal::closure$0
                               at /home/bigfood/programming/namseent/namui/namui-drawer/sys/src/draw/mod.rs:51
  26:     0x7ff700f9a21d - core::iter::traits::iterator::Iterator::for_each::call::closure$0<namui_type::types::render::rendering_tree::DrawCall,namui_drawer_sys::draw::impl$1::draw::draw_internal::closure_env$0>
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\core\src\iter\traits\iterator.rs:854
  27:     0x7ff700e16fdd - core::iter::traits::iterator::Iterator::fold<alloc::vec::into_iter::IntoIter<namui_type::types::render::rendering_tree::DrawCall,alloc::alloc::Global>,tuple$<>,core::iter::traits::iterator::Iterator::for_each::call::closure_env$0<namui_type::types::render
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\core\src\iter\traits\iterator.rs:2639
  28:     0x7ff700e17236 - core::iter::traits::iterator::Iterator::for_each<alloc::vec::into_iter::IntoIter<namui_type::types::render::rendering_tree::DrawCall,alloc::alloc::Global>,namui_drawer_sys::draw::impl$1::draw::draw_internal::closure_env$0>
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\core\src\iter\traits\iterator.rs:857
  29:     0x7ff70104f41c - namui_drawer_sys::draw::impl$1::draw::draw_internal
                               at /home/bigfood/programming/namseent/namui/namui-drawer/sys/src/draw/mod.rs:50
  30:     0x7ff70104f5a9 - namui_drawer_sys::draw::impl$1::draw::draw_internal
                               at /home/bigfood/programming/namseent/namui/namui-drawer/sys/src/draw/mod.rs:46
  31:     0x7ff7010505c3 - namui_drawer_sys::draw::impl$1::draw
                               at /home/bigfood/programming/namseent/namui/namui-drawer/sys/src/draw/mod.rs:117
  32:     0x7ff700f30d9a - namui_drawer_sys::draw
                               at /home/bigfood/programming/namseent/namui/namui-drawer/sys/src/lib.rs:27
  33:     0x7ff700d1fe16 - namui::namui::system::skia::non_wasm::render
                               at /home/bigfood/programming/namseent/namui/namui/src/namui/system/skia/non_wasm.rs:28
  34:     0x7ff700aae1ac - namui::namui::system::drawer::non_wasm::spawn_drawing_thread::closure$0
                               at /home/bigfood/programming/namseent/namui/namui/src/namui/system/drawer/non_wasm.rs:24
  35:     0x7ff700d801b3 - std::sys_common::backtrace::__rust_begin_short_backtrace<namui::namui::system::drawer::non_wasm::spawn_drawing_thread::closure_env$0,tuple$<> >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\sys_common\backtrace.rs:154
  36:     0x7ff700d801b3 - std::sys_common::backtrace::__rust_begin_short_backtrace<namui::namui::system::drawer::non_wasm::spawn_drawing_thread::closure_env$0,tuple$<> >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\sys_common\backtrace.rs:154
  37:     0x7ff700d8dc53 - std::thread::impl$0::spawn_unchecked_::closure$1::closure$0<namui::namui::system::drawer::non_wasm::spawn_drawing_thread::closure_env$0,tuple$<> >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\thread\mod.rs:529
  38:     0x7ff70106b6e3 - core::panic::unwind_safe::impl$23::call_once<tuple$<>,std::thread::impl$0::spawn_unchecked_::closure$1::closure_env$0<namui::namui::system::drawer::non_wasm::spawn_drawing_thread::closure_env$0,tuple$<> > >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\core\src\panic\unwind_safe.rs:271
  39:     0x7ff700f709c7 - std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<std::thread::impl$0::spawn_unchecked_::closure$1::closure_env$0<namui::namui::system::drawer::non_wasm::spawn_drawing_thread::closure_env$0,tuple$<> > >,tuple$<> >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\panicking.rs:504
  40:     0x7ff700f722a3 - std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::impl$2::drop_join_handle_slow::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::fs::read::read::async_fn$0::closure_env$0<std::path::P
  41:     0x7ff700f6f6b1 - std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<std::thread::impl$0::spawn_unchecked_::closure$1::closure_env$0<namui::namui::system::drawer::non_wasm::spawn_drawing_thread::closure_env$0,tuple$<> > > >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\panicking.rs:468
  42:     0x7ff700d8d76b - std::panic::catch_unwind
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\panic.rs:142
  43:     0x7ff700d8d76b - std::thread::impl$0::spawn_unchecked_::closure$1<namui::namui::system::drawer::non_wasm::spawn_drawing_thread::closure_env$0,tuple$<> >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\thread\mod.rs:528
  44:     0x7ff700a76bae - core::ops::function::FnOnce::call_once<std::thread::impl$0::spawn_unchecked_::closure_env$1<namui::namui::system::drawer::non_wasm::spawn_drawing_thread::closure_env$0,tuple$<> >,tuple$<> >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\core\src\ops\function.rs:250
  45:     0x7ff7009bc1dc - std::sys::windows::thread::impl$0::new::thread_start
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\sys\windows\thread.rs:57
  46:     0x7ffb449a257d - BaseThreadInitThunk
  47:     0x7ffb4502aa58 - RtlUserThreadStart
thread 'main' panicked at /home/bigfood/programming/namseent/namui/namui/src/namui/system/skia/non_wasm.rs:21:55:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
stack backtrace:
   0:     0x7ff7009b508a - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\sys_common\backtrace.rs:44
   1:     0x7ff7009e365b - core::fmt::rt::Argument::fmt
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\core\src\fmt\rt.rs:138
   2:     0x7ff7009e365b - core::fmt::write
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\core\src\fmt\mod.rs:1114
   3:     0x7ff7009b0991 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\io\mod.rs:1763
   4:     0x7ff7009b4e0a - std::sys_common::backtrace::_print
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\sys_common\backtrace.rs:47
   5:     0x7ff7009b4e0a - std::sys_common::backtrace::print
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\sys_common\backtrace.rs:34
   6:     0x7ff7009b74da - std::panicking::default_hook::closure$1
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:272
   7:     0x7ff7009b7148 - std::panicking::default_hook
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:292
   8:     0x7ff7009b7b88 - std::panicking::rust_panic_with_hook
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:731
   9:     0x7ff7009b7a6d - std::panicking::begin_panic_handler::closure$0
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:609
  10:     0x7ff7009b5a79 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\sys_common\backtrace.rs:170
  11:     0x7ff7009b7780 - std::panicking::begin_panic_handler
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:597
  12:     0x7ff7023861a7 - core::panicking::panic_fmt
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\core\src\panicking.rs:72
  13:     0x7ff702386763 - core::result::unwrap_failed
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\core\src\result.rs:1652
  14:     0x7ff700a735cc - enum2$<core::result::Result<std::sync::rwlock::RwLockWriteGuard<dyn$<namui_skia::traits::SkSkia,core::marker::Send,core::marker::Sync> >,std::sync::poison::PoisonError<std::sync::rwlock::RwLockWriteGuard<dyn$<namui_skia::traits::SkSkia,core::marker::Send,
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\core\src\result.rs:1077
  15:     0x7ff700d1fcb7 - namui::namui::system::skia::non_wasm::on_window_resize
                               at /home/bigfood/programming/namseent/namui/namui/src/namui/system/skia/non_wasm.rs:21
  16:     0x7ff700f56b3d - namui::namui::system::screen::non_wasm::take_main_thread::closure$0
                               at /home/bigfood/programming/namseent/namui/namui/src/namui/system/screen/non_wasm.rs:58
  17:     0x7ff700d4f01b - winit::platform_impl::platform::event_loop::impl$3::run_on_demand::closure$0<tuple$<>,namui::namui::system::screen::non_wasm::take_main_thread::closure_env$0>
                               at /home/bigfood/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.9/src/platform_impl/windows/event_loop.rs:236
  18:     0x7ff700d4bb98 - alloc::boxed::impl$48::call_mut<tuple$<enum2$<winit::event::Event<tuple$<> > > >,dyn$<core::ops::function::FnMut<tuple$<enum2$<winit::event::Event<tuple$<> > > >,assoc$<Output,tuple$<> > > >,alloc::alloc::Global>
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\alloc\src\boxed.rs:2014
  19:     0x7ff700f5522c - winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure$0<tuple$<> >
                               at /home/bigfood/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.9/src/platform_impl/windows/event_loop/runner.rs:250
  20:     0x7ff70106b784 - core::panic::unwind_safe::impl$23::call_once<tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\core\src\panic\unwind_safe.rs:271
  21:     0x7ff700f70d34 - std::panicking::try::do_call<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > >,tuple$<> >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\panicking.rs:504
  22:     0x7ff700f722a3 - std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::impl$2::drop_join_handle_slow::closure_env$0<tokio::runtime::blocking::task::BlockingTask<tokio::fs::read::read::async_fn$0::closure_env$0<std::path::P
  23:     0x7ff700f6f99a - std::panicking::try<tuple$<>,core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > > >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\panicking.rs:468
  24:     0x7ff700f725e9 - std::panic::catch_unwind<core::panic::unwind_safe::AssertUnwindSafe<winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > >,tuple$<> >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\panic.rs:142
  25:     0x7ff700f538ff - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::catch_unwind<tuple$<>,tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::call_event_handler::closure_env$0<tuple$<> > >
                               at /home/bigfood/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.9/src/platform_impl/windows/event_loop/runner.rs:183
  26:     0x7ff700f5512b - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::call_event_handler<tuple$<> >
                               at /home/bigfood/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.9/src/platform_impl/windows/event_loop/runner.rs:246
  27:     0x7ff700f55523 - winit::platform_impl::platform::event_loop::runner::impl$3::dispatch_buffered_events::closure$0<tuple$<> >
                               at /home/bigfood/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.9/src/platform_impl/windows/event_loop/runner.rs:264
  28:     0x7ff700f52ae8 - enum2$<winit::platform_impl::platform::event_loop::runner::BufferedEvent<tuple$<> > >::dispatch_event<tuple$<>,winit::platform_impl::platform::event_loop::runner::impl$3::dispatch_buffered_events::closure_env$0<tuple$<> > >
                               at /home/bigfood/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.9/src/platform_impl/windows/event_loop/runner.rs:404
  29:     0x7ff700f55460 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::dispatch_buffered_events<tuple$<> >
                               at /home/bigfood/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.9/src/platform_impl/windows/event_loop/runner.rs:264
  30:     0x7ff700f54f18 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::call_new_events<tuple$<> >
                               at /home/bigfood/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.9/src/platform_impl/windows/event_loop/runner.rs:374
  31:     0x7ff700f54887 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::move_state_to<tuple$<> >
                               at /home/bigfood/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.9/src/platform_impl/windows/event_loop/runner.rs:311
  32:     0x7ff700f546a7 - winit::platform_impl::platform::event_loop::runner::EventLoopRunner<tuple$<> >::prepare_wait<tuple$<> >
                               at /home/bigfood/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.9/src/platform_impl/windows/event_loop/runner.rs:211
  33:     0x7ff700d4f397 - winit::platform_impl::platform::event_loop::EventLoop<tuple$<> >::wait_and_dispatch_message<tuple$<> >
                               at /home/bigfood/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.9/src/platform_impl/windows/event_loop.rs:369
  34:     0x7ff700d4ee58 - winit::platform_impl::platform::event_loop::EventLoop<tuple$<> >::run_on_demand<tuple$<>,namui::namui::system::screen::non_wasm::take_main_thread::closure_env$0>
                               at /home/bigfood/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.9/src/platform_impl/windows/event_loop.rs:241
  35:     0x7ff700d4fa22 - winit::platform_impl::platform::event_loop::EventLoop<tuple$<> >::run<tuple$<>,namui::namui::system::screen::non_wasm::take_main_thread::closure_env$0>
                               at /home/bigfood/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.9/src/platform_impl/windows/event_loop.rs:218
  36:     0x7ff700a7169d - winit::event_loop::EventLoop<tuple$<> >::run<tuple$<>,namui::namui::system::screen::non_wasm::take_main_thread::closure_env$0>
                               at /home/bigfood/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.9/src/event_loop.rs:249
  37:     0x7ff7009beb99 - namui::namui::system::screen::non_wasm::take_main_thread
                               at /home/bigfood/programming/namseent/namui/namui/src/namui/system/screen/non_wasm.rs:43
  38:     0x7ff700a5c8a9 - namui::namui::system::take_main_thread
                               at /home/bigfood/programming/namseent/namui/namui/src/namui/system/mod.rs:71
  39:     0x7ff7009be360 - namui::namui::start<image_load_background::App,image_load_background::main::closure_env$0>
                               at /home/bigfood/programming/namseent/namui/namui/src/namui/mod.rs:58
  40:     0x7ff7009a11c9 - image_load_background::main
                               at /home/bigfood/programming/namseent/namui/sample/image-load-background/src/lib.rs:4
  41:     0x7ff7009a1149 - namui_runtime_x86_64_pc_windows_msvc::main
                               at /home/bigfood/programming/namseent/namui/sample/image-load-background/target/namui/src/main.rs:2
  42:     0x7ff7009a10cb - core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\core\src\ops\function.rs:250
  43:     0x7ff7009a108e - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\sys_common\backtrace.rs:154
  44:     0x7ff7009a108e - std::sys_common::backtrace::__rust_begin_short_backtrace<void (*)(),tuple$<> >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\sys_common\backtrace.rs:154
  45:     0x7ff7009a1071 - std::rt::lang_start::closure$0<tuple$<> >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\rt.rs:166
  46:     0x7ff7009aa998 - std::rt::lang_start_internal::closure$2
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\rt.rs:148
  47:     0x7ff7009aa998 - std::panicking::try::do_call
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:504
  48:     0x7ff7009aa998 - std::panicking::try
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panicking.rs:468
  49:     0x7ff7009aa998 - std::panic::catch_unwind
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\panic.rs:142
  50:     0x7ff7009aa998 - std::rt::lang_start_internal
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library\std\src\rt.rs:148
  51:     0x7ff7009a104a - std::rt::lang_start<tuple$<> >
                               at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1\library\std\src\rt.rs:165
  52:     0x7ff7009a1169 - main
  53:     0x7ff702384e14 - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  54:     0x7ff702384e14 - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  55:     0x7ffb449a257d - BaseThreadInitThunk
  56:     0x7ffb4502aa58 - RtlUserThreadStart
```

### Steps to Reproduce

1. Go to `namui/sample/image-load-background`
2. Build and run

**Comment by bigfoodK** [comment]
Closed with #774
