### ISSUE TITLE
[Bug]: Images not be rendered gradually

### ISSUE THREAD

**Issue by bigfoodK** [NamseEnt/namseent#873]
### Expected Behavior

Keep render images

### Actual Behavior

Image not be rendered with error
```text
Uncaught (in promise) RangeError: Array buffer allocation failed
    at arrayBufferConstructor_DoNotInitialize (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new File (@bjorn3_browser_wasi_shim.js?v=b0181aa0:1458:17)
    at fds.ts:27:9
    at Array.map (<anonymous>)
    at makeDictionaryTree (fds.ts:23:24)
    at fds.ts:30:39
    at Array.map (<anonymous>)
    at makeDictionaryTree (fds.ts:23:24)
    at fds.ts:30:39
```

![animation](https://github.com/NamseEnt/namseent/assets/38313680/308fa709-b677-433a-9da5-af00f5df601a)

### Steps to Reproduce

Render multiple image reapeatly

Run jigcle in 8943c6a80fae1e44bb7f4a611a51a83b07db22d0

### Other Info

Maybe right or maybe not

**Comment by namse** [comment]
The `fds.ts` on your error log is no longer used. I guess it might be fixed after sqlite bundle system. please try again.
